CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR NOT NULL UNIQUE,
    password VARCHAR
);

CREATE TABLE IF NOT EXISTS Locations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR                       NOT NULL,
    user_id   INTEGER REFERENCES users (id) NOT NULL,
    latitude  DECIMAL                       NOT NULL,
    longitude DECIMAL                       NOT NULL,
    CONSTRAINT user_coordinates UNIQUE (user_id, latitude, longitude)
);

CREATE TABLE IF NOT EXISTS Sessions
(
    id         uuid                          NOT NULL PRIMARY KEY,
    user_id    INTEGER REFERENCES users (id) NOT NULL,
    expires_at TIMESTAMP                     NOT NULL
);

CREATE INDEX expires_at ON Sessions (expires_at);